#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start Nginx Service
sudo service nginx start

# Modify the Nginx configuration to include the redirection
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
  
	location /redirect_me {
  		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart
