#!/usr/bin/env bash
#configure a new server with nginx and xustom HTTP header that returns the hostname
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R ubuntu:ubuntu /var/www/html
sudo chmod -R 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/server_name example.com;/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
