#!/usr/bin/env bash
#set up Haproxy to load balance requests for to servers
sudo apt update
sudo apt -y install haproxy
echo 'frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server web-01 100.25.215.65:80 check
        server web-02 34.207.154.239:80 check' >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
