#!/usr/bin/env bash
#script to create MYSQL dump and compress it

if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi
MYSQL_ROOT_PASSWORD=$1

DATE=$(date +"%d-%m-$Y")

mysqldump -u root -p$MYSQL_ROOT_PASSWORD --all-databases > backup.sql

tar -czvf $DATE.tar.gz backup.sql

