#!/usr/bin/env bash
#script that displays indefinitely and displays custom string
# if it recieved a SIGTERM signal
terminate() {
	echo "I am invincible!!!"
}
trap 'terminate' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
