#!/usr/bin/env bash
# 4 bad luck 8 good luck Best School all the time
n=0
while [ $n -lt 10 ]; do
	if [ $n -eq 3 ]; then
		echo "bad luck"
	elif [ $n -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
